In [249]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.preprocessing import*
%matplotlib inline

from sklearn import model_selection
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split


In [250]:
df=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/balance-scale/balance-scale.data')
df.head(15)

B  1  1.1  1.2  1.3
0   R  1    1    1    2
1   R  1    1    1    3
2   R  1    1    1    4
3   R  1    1    1    5
4   R  1    1    2    1
5   R  1    1    2    2
6   R  1    1    2    3
7   R  1    1    2    4
8   R  1    1    2    5
9   R  1    1    3    1
10  R  1    1    3    2
11  R  1    1    3    3
12  R  1    1    3    4
13  R  1    1    3    5
14  R  1    1    4    1

In [251]:
df.shape,df.size

((624, 5), 3120)

In [252]:
y=df.iloc[:,0]
y.head(15)

0     R
1     R
2     R
3     R
4     R
5     R
6     R
7     R
8     R
9     R
10    R
11    R
12    R
13    R
14    R
Name: B, dtype: object

In [253]:
x=df.iloc[:,1:]
x.head(15)

1  1.1  1.2  1.3
0   1    1    1    2
1   1    1    1    3
2   1    1    1    4
3   1    1    1    5
4   1    1    2    1
5   1    1    2    2
6   1    1    2    3
7   1    1    2    4
8   1    1    2    5
9   1    1    3    1
10  1    1    3    2
11  1    1    3    3
12  1    1    3    4
13  1    1    3    5
14  1    1    4    1

In [254]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3,random_state=42)

In [255]:
from sklearn.tree import *

In [256]:
m=DecisionTreeClassifier(max_leaf_nodes=50,random_state=105)

In [257]:
m.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=50,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=105,
            splitter='best')

In [258]:
predict = m.predict(x_test)

In [259]:
from sklearn import metrics
metrics.accuracy_score(y_test,predict)

0.8031914893617021

In [260]:
from sklearn.metrics import classification_report
print(classification_report(y_test,predict))

             precision    recall  f1-score   support

          B       0.00      0.00      0.00        12
          L       0.83      0.86      0.85        87
          R       0.94      0.85      0.89        89

avg / total       0.83      0.80      0.82       188



In [261]:
from sklearn.metrics import confusion_matrix

In [262]:
confusion_matrix(y_test,predict)

array([[ 0,  8,  4],
       [11, 75,  1],
       [ 6,  7, 76]], dtype=int64)

In [263]:
m1=DecisionTreeClassifier(criterion="entropy",max_depth=10)

In [264]:
m1.fit(x_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=10,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [265]:
predict1 = m1.predict(x_test)

In [267]:
metrics.accuracy_score(y_test,predict1)

0.8085106382978723

In [268]:
print(classification_report(y_test,predict1))

             precision    recall  f1-score   support

          B       0.11      0.25      0.15        12
          L       0.89      0.85      0.87        87
          R       0.96      0.84      0.90        89

avg / total       0.87      0.81      0.84       188



In [269]:
confusion_matrix(y_test,predict1)

array([[ 3,  6,  3],
       [13, 74,  0],
       [11,  3, 75]], dtype=int64)

In [270]:
from sklearn.ensemble import RandomForestClassifier

In [271]:
m2=RandomForestClassifier(random_state=0,max_depth=10,n_jobs=2)

In [272]:
m2.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=10, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [273]:

predict2  = m2.predict((x_test))

In [274]:
metrics.accuracy_score(y_test,predict2)

0.8351063829787234

In [275]:
confusion_matrix(y_test,predict2)

array([[ 1,  7,  4],
       [ 9, 77,  1],
       [ 6,  4, 79]], dtype=int64)

In [276]:
m3=RandomForestClassifier(criterion="entropy",n_jobs = 2,random_state=10)

In [277]:
m3.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=10, verbose=0, warm_start=False)

In [278]:
predict3 = m3.predict(x_test)

In [279]:
metrics.accuracy_score(y_test,predict3)

0.8351063829787234

In [280]:
print(classification_report(y_test,predict3))

             precision    recall  f1-score   support

          B       0.00      0.00      0.00        12
          L       0.89      0.90      0.89        87
          R       0.92      0.89      0.90        89

avg / total       0.85      0.84      0.84       188



In [281]:
confusion_matrix(y_test,predict3)

array([[ 0,  5,  7],
       [ 9, 78,  0],
       [ 5,  5, 79]], dtype=int64)