In [2]:
# Question 1
# Using Bayes’ Theorem
# P(Yes|Sunny)= (P(Sunny|Yes)P(Yes))/P(Sunny)
# P(Sunny|Yes) = 1/3
# P(Yes) = 9/14
# P(Sunny) = 5/14
print("P(Yes|Sunny) = 3/5")

P(Yes|Sunny) = 3/5


In [36]:
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.preprocessing import*
%matplotlib inline

In [37]:
#Question 2
from sklearn.datasets import load_iris

In [38]:
iris=load_iris()


In [40]:
x=iris.data
x.shape


(150, 4)

In [41]:
y=iris.target
y.shape

(150,)

In [42]:
x.size,y.size

(600, 150)

In [43]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

In [44]:
# Using GaussianNB Algorithm for Normal distribution 
from sklearn.naive_bayes import GaussianNB

In [45]:
m=GaussianNB()
m.fit(x_train,y_train)

GaussianNB(priors=None)

In [46]:
a= m.predict(x_test)
a

array([1, 0, 1, 2, 1, 1, 0, 2, 2, 0, 0, 0, 1, 2, 2, 1, 1, 1, 0, 2, 2, 0,
       2, 0, 0, 2, 2, 1, 2, 2, 0, 2, 1, 2, 1, 0, 2, 1, 2, 1, 1, 1, 0, 2,
       0])

In [47]:
from sklearn.metrics import confusion_matrix

In [49]:
confusion_matrix(y_test,a)

array([[13,  0,  0],
       [ 0, 13,  1],
       [ 0,  2, 16]], dtype=int64)

In [50]:
from sklearn.metrics import *
from sklearn.metrics import classification_report

In [51]:
print(classification_report(y_test, a))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        13
          1       0.87      0.93      0.90        14
          2       0.94      0.89      0.91        18

avg / total       0.93      0.93      0.93        45



In [52]:
# using MultinomialNB for Multinomially Distribution 
from sklearn.naive_bayes import MultinomialNB

m1=MultinomialNB()
m1.fit(x_train,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [53]:
pre= m1.predict(x_test)
pre

array([1, 0, 1, 2, 1, 1, 0, 2, 2, 0, 0, 0, 1, 2, 2, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 0, 2, 1, 1, 1, 1, 0, 1, 1, 2, 1, 0, 1, 1, 2, 1, 1, 1, 0, 1,
       0])

In [54]:
confusion_matrix(y_test,pre)

array([[13,  0,  0],
       [ 0, 14,  0],
       [ 0, 10,  8]], dtype=int64)

In [55]:
print(classification_report(y_test,pre))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        13
          1       0.58      1.00      0.74        14
          2       1.00      0.44      0.62        18

avg / total       0.87      0.78      0.76        45

