In [2]:
#importing packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
from sklearn.datasets import load_digits

In [4]:
digit=load_digits()
x=(digit.data)
y=(digit.target)

In [5]:
from sklearn.preprocessing import StandardScaler

In [6]:
x_Std=StandardScaler().fit_transform(x)
x_Std

array([[ 0.        , -0.33501649, -0.04308102, ..., -1.14664746,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  0.54856067,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -1.09493684, ...,  1.56568555,
         1.6951369 , -0.19600752],
       ...,
       [ 0.        , -0.33501649, -0.88456568, ..., -0.12952258,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649, -0.67419451, ...,  0.8876023 ,
        -0.5056698 , -0.19600752],
       [ 0.        , -0.33501649,  1.00877481, ...,  0.8876023 ,
        -0.26113572, -0.19600752]])

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x , y, test_size=0.30, random_state = 101)

In [10]:
from sklearn.decomposition import PCA
pca = PCA(n_components=30)

In [11]:
PC = pca.fit_transform(x_Std)

In [12]:
prinDf = pd.DataFrame(data = PC)

In [13]:
prinDf

0         1         2         3         4         5         6   \
0     1.914213 -0.954501 -3.946035  2.028715 -0.267160  0.530320 -1.415327   
1     0.588980  0.924635  3.924756 -1.779851 -0.993429 -0.675586  1.878556   
2     1.302040 -0.317195  3.023331 -2.043353 -2.081185  0.935099 -1.296087   
3    -3.020770 -0.868771 -0.801742 -2.187034 -0.556832  0.727161  0.959832   
4     4.528950 -1.093480  0.973116 -1.419515 -1.715091  1.431499  1.073526   
5    -1.301890 -1.148186 -1.574609 -2.413646 -0.630977  0.740887  1.306736   
6     1.434222 -2.957842  2.831278 -0.076963  0.523053  0.010800  0.983699   
7     0.614240  5.462186  0.658244  0.434427  0.850139 -0.954120 -1.833796   
8    -1.098450 -0.665822 -0.041023 -1.102523 -0.900734  0.755144 -0.966447   
9    -0.537970 -0.777502 -1.568925 -0.759959 -0.121412 -0.600917  0.675375   
10    3.378759 -0.495768 -2.280895  1.429195  0.006586 -0.150519 -0.739188   
11    2.063345  2.016678  1.540476 -4.773149 -2.194263  0.344444  3.084378   
12   -1.937012 -1.815244  2.801369 -0.786559  3.025814 -0.384545 -0.647759   
13   -3.258076  2.149124 -1.615648 -1.798926 -0.745369  1.828761  0.763437   
14    5.458744  0.025132  0.182526 -0.119626 -0.541039  0.104776  1.083151   
15   -3.877037  2.606819  1.858531  5.454018  0.615492  0.988588  3.602248   
16    0.921352 -3.262241  3.401441 -3.227338  1.096506  0.081924 -0.573207   
17    1.415335  1.954481  0.560573 -0.368838 -1.302496 -1.883583 -1.063359   
18   -0.926521  2.253016  1.532926  0.111957 -1.640289  0.261401 -0.069232   
19   -2.370963 -2.931918 -0.381367 -3.232755  2.084194  0.545276 -0.615817   
20    2.001900 -1.319748 -2.570949  0.855349 -0.565549 -1.017594 -0.811938   
21    1.694878  2.075386  0.885988 -4.388593 -1.446104 -0.307202  3.643110   
22   -3.114571 -1.058974  2.451496 -0.547902  0.761786 -0.012742 -1.890126   
23   -1.469419  3.910390 -2.078331 -0.869932  0.203798  0.689480 -0.288149   
24    4.003334 -0.322215  0.587683 -2.740553 -1.513572  0.676012  2.088608   
25   -0.376723  0.525115  1.356039  3.106103  0.926282 -1.029442  1.450002   
26    1.286727 -3.969441  2.542965  0.936662  0.282406  0.352533  1.026728   
27    3.842317  3.478237 -1.569508 -1.675848 -0.274098 -0.345155 -0.150116   
28   -0.166536  0.934113  1.259153 -0.086535 -1.045706  0.362849 -0.877859   
29   -2.014424 -2.376848 -0.707911 -3.515246  1.168360  0.694339  0.206769   
...        ...       ...       ...       ...       ...       ...       ...   
1767  4.958572 -1.159631  0.645673 -1.495332 -1.408057  0.580156  2.222039   
1768  1.009034 -3.325936 -0.584416  0.907499 -0.665958  0.398911 -1.279881   
1769 -0.542839 -0.492983 -3.138884  0.952796  0.732359 -1.169407  1.900078   
1770 -3.314655  1.510566 -0.820053 -1.838154 -1.474764  1.442571  2.178255   
1771  2.128214 -2.822365  3.623381 -1.087847 -0.085811  0.389269  1.443190   
1772 -1.814030  1.197999 -3.113637 -1.063793 -1.806731  0.021242  1.294927   
1773  1.374679 -4.417770  0.544579  0.931153  1.151814 -0.342607  0.125692   
1774  0.762953  0.643400  3.119027 -0.449234 -2.038236 -0.268185 -0.225365   
1775 -0.433045  3.216018  2.011169 -0.229289 -1.509373 -1.166784 -2.852411   
1776 -0.525867 -1.154642 -1.889820  0.953329  0.807098 -1.084827  1.495916   
1777  5.106683 -0.289142  0.341404 -1.773520 -2.469440  1.596641  0.884988   
1778  5.900098 -1.710245  1.858914  0.171270 -4.529269  4.714893  0.440310   
1779  1.597139  4.676426  0.469294 -0.503393 -0.074219 -1.780227 -2.550971   
1780 -5.137834 -0.191047  2.223968  2.046419 -0.885010  3.406910 -0.342150   
1781 -1.416098 -1.031487  1.196075  0.841547 -2.197926  2.483206  0.573366   
1782 -4.272989 -1.355838  3.059714  0.367657  1.045054  0.747238  0.006403   
1783 -3.136887 -1.411702  2.238419 -0.085148  0.779770  0.689887 -1.289880   
1784  1.568544 -0.438605 -1.840598 -0.847231  0.413576 -1.193754  2.474075   
1785  0.058277  1.978137  1.807598  1.282993 -1.856845 -0.847040 -3.167644   
1786 -0.711454  0.253344 -2.934788

In [14]:
pca.explained_variance_ratio_

array([0.12033916, 0.09561054, 0.08444415, 0.06498408, 0.04860155,
       0.0421412 , 0.03942083, 0.03389381, 0.02998221, 0.02932003,
       0.02781805, 0.02577055, 0.02275303, 0.0222718 , 0.02165229,
       0.01914164, 0.01775545, 0.01638066, 0.01596452, 0.01489187,
       0.01347944, 0.01271899, 0.01165795, 0.01057427, 0.00975146,
       0.00944324, 0.00862928, 0.00836219, 0.00796439, 0.00744986])

In [15]:
from sklearn.linear_model import LogisticRegression

In [18]:
prinDf_train,prinDf_test,y_train,y_test = train_test_split(prinDf,y,test_size = 0.3)

In [19]:
m=LogisticRegression()
m.fit(prinDf_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [20]:
pred=m.predict(prinDf_test)
pred

array([7, 3, 3, 2, 7, 2, 9, 5, 1, 4, 7, 8, 4, 5, 7, 3, 5, 4, 9, 9, 3, 1,
       1, 8, 0, 4, 0, 2, 4, 6, 0, 0, 1, 3, 2, 9, 1, 9, 4, 4, 6, 4, 1, 0,
       2, 4, 2, 6, 9, 1, 9, 9, 5, 2, 9, 4, 7, 6, 1, 8, 1, 6, 8, 2, 0, 3,
       5, 8, 5, 3, 0, 1, 2, 6, 5, 1, 1, 2, 6, 1, 0, 2, 5, 6, 8, 3, 1, 7,
       5, 4, 1, 1, 1, 7, 7, 3, 7, 9, 8, 1, 0, 9, 8, 3, 6, 6, 1, 5, 7, 3,
       4, 4, 1, 1, 8, 9, 5, 1, 6, 6, 9, 8, 4, 4, 3, 7, 2, 5, 1, 8, 6, 0,
       1, 2, 3, 3, 7, 4, 7, 2, 7, 5, 7, 1, 7, 7, 6, 5, 6, 4, 6, 0, 7, 1,
       7, 1, 6, 9, 0, 4, 3, 8, 2, 1, 7, 5, 6, 7, 2, 2, 4, 8, 1, 8, 7, 8,
       5, 6, 3, 3, 8, 2, 1, 2, 3, 1, 5, 8, 1, 3, 6, 6, 4, 3, 6, 2, 3, 7,
       5, 1, 9, 6, 6, 5, 3, 1, 0, 7, 0, 4, 8, 4, 7, 6, 6, 6, 0, 4, 6, 2,
       8, 5, 0, 7, 5, 2, 6, 2, 8, 3, 0, 6, 8, 9, 8, 0, 7, 8, 7, 4, 5, 2,
       3, 0, 4, 5, 2, 5, 1, 8, 1, 4, 5, 4, 4, 3, 4, 7, 0, 9, 3, 8, 3, 9,
       6, 5, 7, 5, 9, 4, 7, 7, 8, 8, 3, 7, 6, 5, 2, 3, 5, 3, 6, 8, 2, 0,
       4, 3, 6, 8, 7, 7, 8, 0, 1, 3, 6, 5, 5, 8, 6,

In [21]:
from sklearn import metrics
metrics.accuracy_score(y_test,pred)

0.95

In [22]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        47
          1       0.92      0.97      0.94        58
          2       0.98      1.00      0.99        49
          3       0.98      0.92      0.95        61
          4       0.97      0.98      0.97        57
          5       0.95      0.97      0.96        63
          6       0.97      0.98      0.97        58
          7       1.00      0.98      0.99        58
          8       0.79      0.79      0.79        43
          9       0.91      0.87      0.89        46

avg / total       0.95      0.95      0.95       540



In [23]:
from sklearn.metrics import confusion_matrix

In [24]:
confusion_matrix(y_test,pred)

array([[47,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 56,  0,  0,  0,  0,  0,  0,  1,  1],
       [ 0,  0, 49,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1, 56,  0,  0,  0,  0,  4,  0],
       [ 0,  1,  0,  0, 56,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 61,  0,  0,  0,  2],
       [ 0,  0,  0,  0,  1,  0, 57,  0,  0,  0],
       [ 0,  0,  0,  0,  1,  0,  0, 57,  0,  0],
       [ 0,  4,  0,  1,  0,  1,  2,  0, 34,  1],
       [ 0,  0,  0,  0,  0,  2,  0,  0,  4, 40]], dtype=int64)