In [2]:
import matplotlib.pyplot as plt
import seaborn as sn
import pandas as pd
import numpy as np
%matplotlib inline

In [3]:
from sklearn.datasets import load_wine

In [4]:
wines = load_wine()

In [5]:
x=(wines.data)
y=(wines.target)

In [6]:
x.shape,x.size

((178, 13), 2314)

In [7]:
y.shape,y.size

((178,), 178)

In [10]:
from sklearn.ensemble import BaggingClassifier
from sklearn import tree

In [12]:
model=tree.DecisionTreeClassifier()

In [13]:
num_tree =100

In [14]:
model1=BaggingClassifier(base_estimator=model)

In [15]:
model1

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=10, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [16]:
from  sklearn.model_selection  import train_test_split

In [17]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)

In [18]:
model1.fit(x_train,y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=10, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [19]:
pred=model1.predict(x_test)


In [20]:
from sklearn import metrics

In [21]:
metrics.accuracy_score(y_test,pred)

0.9629629629629629

In [22]:
from sklearn.metrics import classification_report
print(classification_report(y_test,pred))

             precision    recall  f1-score   support

          0       0.95      0.95      0.95        20
          1       0.96      0.96      0.96        23
          2       1.00      1.00      1.00        11

avg / total       0.96      0.96      0.96        54



In [23]:
from sklearn.metrics import confusion_matrix

In [24]:
confusion_matrix(y_test,pred)

array([[19,  1,  0],
       [ 1, 22,  0],
       [ 0,  0, 11]], dtype=int64)

In [25]:
from sklearn.ensemble import RandomForestClassifier

In [51]:
m=RandomForestClassifier(random_state=1,max_depth=10 )

In [52]:
m.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=10, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=1, verbose=0, warm_start=False)

In [53]:
pred1=m.predict(x_test)

In [54]:
metrics.accuracy_score(y_test,pred1)

1.0

In [55]:
print(classification_report(y_test,pred1))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        20
          1       1.00      1.00      1.00        23
          2       1.00      1.00      1.00        11

avg / total       1.00      1.00      1.00        54



In [56]:
confusion_matrix(y_test,pred1)

array([[20,  0,  0],
       [ 0, 23,  0],
       [ 0,  0, 11]], dtype=int64)

In [32]:
from sklearn.ensemble import GradientBoostingClassifier

In [33]:
model3=GradientBoostingClassifier()
model3

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [34]:
model3.fit(x_train,y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_decrease=0.0, min_impurity_split=None,
              min_samples_leaf=1, min_samples_split=2,
              min_weight_fraction_leaf=0.0, n_estimators=100,
              presort='auto', random_state=None, subsample=1.0, verbose=0,
              warm_start=False)

In [35]:
pred2=model3.predict(x_test)

In [36]:
metrics.accuracy_score(y_test,pred2)

0.9444444444444444

In [37]:
confusion_matrix(y_test,pred2)

array([[19,  1,  0],
       [ 2, 21,  0],
       [ 0,  0, 11]], dtype=int64)

In [38]:
print(classification_report(y_test,pred2))

             precision    recall  f1-score   support

          0       0.90      0.95      0.93        20
          1       0.95      0.91      0.93        23
          2       1.00      1.00      1.00        11

avg / total       0.95      0.94      0.94        54



In [40]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression


In [57]:
m2=LogisticRegression()
m3=tree.DecisionTreeClassifier()
m4=SVC()

In [58]:
estimators=[]

In [59]:
estimators.append(('LogisticRegression',m2))
estimators.append(('DecisionTreeClassifie',m3))
estimators.append(('svm',m4))

In [60]:
from sklearn.ensemble import VotingClassifier

In [61]:
ensemble=VotingClassifier(estimators)

In [62]:
ensemble.fit(x_train,y_train)

VotingClassifier(estimators=[('LogisticRegression', LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False))...,
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False))],
         flatten_transform=None, n_jobs=1, voting='hard', weights=None)

In [63]:
pred4=ensemble.predict(x_test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [64]:
metrics.accuracy_score(y_test,pred4)

0.9629629629629629

In [65]:
confusion_matrix(y_test,pred4)

array([[18,  2,  0],
       [ 0, 23,  0],
       [ 0,  0, 11]], dtype=int64)

In [66]:
print(classification_report(y_test,pred4))

             precision    recall  f1-score   support

          0       1.00      0.90      0.95        20
          1       0.92      1.00      0.96        23
          2       1.00      1.00      1.00        11

avg / total       0.97      0.96      0.96        54

